### ISSUE TITLE
Server crashes after placing GalactiCraft Laser Turret (and world is not fixable with forge config B:removeErroringTileEntities=true)

### ISSUE THREAD

**Issue by erickloss** [StormcodersDE/Minecraft-Time#29]
**Beschreibe den Bug**
Server crashes when a player connects near to a / placed a GalactiCraft Laser Turret.

**Wie man den Bug reproduzieren kann**
Schritte:
1. Create new World
2. place Laser Turret
3. Server crashes
4. Relog with client
5. Server crashes
6. set `removeError***=true` in config/forge.cfg
7. Restart Server / Relog client
8. Server crashes -> broken entities not fixed / removed

Seems to be:
https://github.com/micdoodle8/Galacticraft/issues/3807

Version Check on server:
```
bash-4.4# ls -la | grep Galac
-rw-r--r--    1 root     root       4097186 Feb 22 17:00 Galacticraft-Planets-1.12.2-4.0.2.237.jar
-rw-r--r--    1 root     root      10419944 Feb 22 17:00 GalacticraftCore-1.12.2-4.0.2.237.jar
```
Important:
The world is not fixable by setting the
`config/forge.cfg` entries, as described in:
https://github.com/micdoodle8/Galacticraft/issues/3807#issuecomment-538683285
My question: should it be? Or how to fix a broken world state otherwise?

Exception: 
```
java.lang.NoSuchFieldError: timeSinceShot
        at micdoodle8.mods.galacticraft.planets.venus.tile.TileEntityLaserTurret.<init>(TileEntityLaserTurret.java:98)
        at micdoodle8.mods.galacticraft.planets.venus.blocks.BlockLaserTurret.func_149915_a(BlockLaserTurret.java:105)
        at net.minecraft.block.Block.createTileEntity(Block.java:1274)
        at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782)
        at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800)
        at net.minecraft.world.World.func_175625_s(World.java:2402)
        at micdoodle8.mods.galacticraft.core.network.PacketSimple.handleServerSide(PacketSimple.java:1313)
        at micdoodle8.mods.galacticraft.core.network.GalacticraftPacketHandler.tick(GalacticraftPacketHandler.java:68)
        at micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onWorldTick(TickHandlerServer.java:644)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1388_TickHandlerServer_onWorldTick_WorldTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```
full error log:
https://pastebin.com/y2SrwkYr

**Desktop (bitte vervollständige diese Informationen):**
 - Alpine (docker base image openjdk8-alpine)
 - Time 1.3 Server Pack

Cheers :)

**Comment by lays24mc** [comment]
No more update vor time. Deactivate the turret in the config. the turret ist BETA!
